spring:
  application:
    name: eureka-server

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:9200/eureka/,http://peer3:9300/eureka/
server:
  port: 9100
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:9100/eureka/,http://peer3:9300/eureka/
server:
  port: 9200
---

spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:9100/eureka/,http://peer2:9200/eureka/
server:
  port: 9300

---
spring:
  profiles: standalone
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761